// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA464d9AimhAfSAT0mbFT29kqZVCu2A170',
    appId: '1:468958018042:web:1aec9ade9a000d4c1b4c43',
    messagingSenderId: '468958018042',
    projectId: 'lookup-j8h1i6',
    authDomain: 'lookup-j8h1i6.firebaseapp.com',
    storageBucket: 'lookup-j8h1i6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVTpzF2vjfBQr4lvEWinIuEd10IQBlsc',
    appId: '1:468958018042:android:c94c3cfe6625cbfc1b4c43',
    messagingSenderId: '468958018042',
    projectId: 'lookup-j8h1i6',
    storageBucket: 'lookup-j8h1i6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-zXHSNkU-lQx4LpzLKLkakRrgNP-kuA',
    appId: '1:468958018042:ios:6b36238310f9571f1b4c43',
    messagingSenderId: '468958018042',
    projectId: 'lookup-j8h1i6',
    storageBucket: 'lookup-j8h1i6.appspot.com',
    iosBundleId: 'com.example.lookup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-zXHSNkU-lQx4LpzLKLkakRrgNP-kuA',
    appId: '1:468958018042:ios:6b36238310f9571f1b4c43',
    messagingSenderId: '468958018042',
    projectId: 'lookup-j8h1i6',
    storageBucket: 'lookup-j8h1i6.appspot.com',
    iosBundleId: 'com.example.lookup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA464d9AimhAfSAT0mbFT29kqZVCu2A170',
    appId: '1:468958018042:web:b11f7586baccb4bc1b4c43',
    messagingSenderId: '468958018042',
    projectId: 'lookup-j8h1i6',
    authDomain: 'lookup-j8h1i6.firebaseapp.com',
    storageBucket: 'lookup-j8h1i6.appspot.com',
  );
}
